---
platform: linux
image_resource:
    type: docker-image
    source:
        repository: node
inputs:
    - name: source-code

run:
    path: source-code/ci/script/script-1.sh
outputs:
    - name: source-code
      path: .