---
resource_types:
    - name: concourse-ssh-resource
      type: docker-image
      source:
        repository: edtan1/concourse-ssh-resource

    - name: slack-alert
      type: docker-image
      source:
        repository: arbourd/concourse-slack-alert-resource

resources:
    - name: source-code
      type: git
      icon: github
      source:
        uri: https://github.com/DipayanP007/node-hello.git
        branch: main
    - name: notify
      type: slack-alert
      source:
        url: https://hooks.slack.com/services/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
    
    
    
    - name: artifact-repo
      type: s3
      source:
        bucket: pluralsight-concourse
        region_name: us-west-2
        access_key_id: AKIASZ3GEBPJY4LBR5ZT
        secret_access_key: 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
        versioned_file: node-hello-0.0.1.tgz

jobs:
    - name: packing
      build_log_retention:
        builds: 5
        minimum_succeeded_builds: 1
      plan:
        - get: source-code
          trigger: true
        - task: npm-pack
          file: source-code/ci/Tasks/pack-task.yml
          on_success:
            put: notify
            params:
              alert_type: success
          on_failure:
            put: notify
            params:
              alert_type: failure
          on_abort:
            put: notify
            params:
              alert_type: abort
          on_error:
            put: notify
            params:
              alert_type: error
          ensure:
            put: notify
            params:
              message: Done
        - put: artifact-repo
          params:
            file: source-code/node-hello-0.0.1.tgz