---
resource_types:
    - name: concourse-ssh-resource
      type: docker-image
      source:
        repository: edtan1/concourse-ssh-resource

    - name: slack-alert
      type: docker-image
      source:
        repository: arbourd/concourse-slack-alert-resource

resources:
    - name: source-code
      type: git
      icon: github
      source:
        uri: https://github.com/DipayanP007/node-hello.git
        branch: main
    
    
    
    - name: artifact-repo
      type: s3
      source:
        bucket: pluralsight-concourse
        region_name: us-west-2
        access_key_id: 
        secret_access_key: 
        versioned_file: node-hello-0.0.1.tgz

jobs:
    - name: packing
      build_log_retention:
        builds: 5
        minimum_succeeded_builds: 1
      plan:
        - get: source-code
          trigger: true
        - task: npm-pack
          file: source-code/ci/Tasks/pack-task.yml
          
        - task: check
          config:
            platform: linux
            image_resource: 
              type: docker-image
              source: {repository: ubuntu}
            inputs: 
              - name: source-code
            run:
              path: ls
              args:
                - source-code/


        - put: artifact-repo
          params:
            file: source-code/node-hello-0.0.1.tgz
